//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBBEgitim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvurular
    {
        public int id { get; set; }
        public int kategoriId { get; set; }
        public Nullable<int> egitimId { get; set; }
        public Nullable<int> basvuruDurumId { get; set; }
        public Nullable<int> cinsiyetId { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tcNo { get; set; }
        public string dogumYeri { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string nufusaKayitliYer { get; set; }
        public string meslek { get; set; }
        public string meslekOdasi { get; set; }
        public string sicilNo { get; set; }
        public string vergiDairesi { get; set; }
        public string vergiNo { get; set; }
        public string temelUzmanlikAlani { get; set; }
        public string altUzmanlikAlani { get; set; }
        public string unvan { get; set; }
        public Nullable<int> ogrenimDuzeyiId { get; set; }
        public Nullable<int> universiteId { get; set; }
        public string bolum { get; set; }
        public Nullable<System.DateTime> mezuniyetTarihi { get; set; }
        public string diplomaNo { get; set; }
        public string yabanciDil1 { get; set; }
        public Nullable<int> yabanciDilSeviyeId1 { get; set; }
        public string yabanciDil2 { get; set; }
        public Nullable<int> yabanciDilSeviyeId2 { get; set; }
        public string yabanciDil3 { get; set; }
        public Nullable<int> yabanciDilSeviyeId3 { get; set; }
        public string adres { get; set; }
        public Nullable<int> ilId { get; set; }
        public string postaKodu { get; set; }
        public string eposta { get; set; }
        public string gsm { get; set; }
        public string tel { get; set; }
        public string referansNo { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public string ip { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<bool> kabul { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public Nullable<bool> faturaBasildiMi { get; set; }
        public string faturaNo { get; set; }
        public Nullable<System.DateTime> faturaTarihi { get; set; }
        public string faturaReferansNo { get; set; }
        public Nullable<bool> sertifikaHakki { get; set; }
        public Nullable<System.DateTime> sertifikaBasimTarihi { get; set; }
        public string sertifikaNo { get; set; }
        public Nullable<bool> odeme { get; set; }
        public Nullable<System.DateTime> odemeTarihi { get; set; }
        public string dekontNo { get; set; }
        public Nullable<int> odemeSekliId { get; set; }
        public Nullable<decimal> iadeTutari { get; set; }
        public Nullable<System.DateTime> iadeTarihi { get; set; }
        public Nullable<int> eskiId { get; set; }
        public Nullable<int> eskiEgitimId { get; set; }
        public Nullable<bool> kurumsalFatura { get; set; }
        public string firmaAdi { get; set; }
        public string firmaAdi2 { get; set; }
    }
}
