//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBBEgitim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitimler
    {
        public int id { get; set; }
        public int kategoriId { get; set; }
        public string egitimAdi { get; set; }
        public Nullable<int> egitimTipId { get; set; }
        public Nullable<int> egitimDurumId { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> baslangicTarihi { get; set; }
        public Nullable<System.DateTime> bitisTarihi { get; set; }
        public string tarihAciklama { get; set; }
        public string saatAraligi { get; set; }
        public Nullable<int> saat { get; set; }
        public string egitimYeri { get; set; }
        public Nullable<int> ilId { get; set; }
        public Nullable<int> kontenjan { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public Nullable<decimal> avUcret { get; set; }
        public Nullable<decimal> digerUcret { get; set; }
        public string sertifika { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public Nullable<bool> aktif { get; set; }
        public string eskiId { get; set; }
        public string sertifikaEgitimAdi { get; set; }
        public string sertifikaEgitimTipi { get; set; }
        public Nullable<bool> avukat { get; set; }
        public Nullable<bool> ilbazli { get; set; }
        public Nullable<bool> gorunurluk { get; set; }
    }
}
