//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBBEgitim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TBBEgitimDbEntities : DbContext
    {
        public TBBEgitimDbEntities()
            : base("name=TBBEgitimDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basvurular> Basvurular { get; set; }
        public virtual DbSet<Egitimler> Egitimler { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
    }
}
